name: myworkflow

on: 
  push:

jobs:
  test:
     runs-on: ubuntu-latest

     steps: 
       - name: System Info
         run: |
           mkdir demo
           ls
           echo "starting "
           sleep 10 
           echo "finished"
  
          
     
