name: multiple steps-workflow

on: 
  push:

jobs:
  build:
     runs-on: ubuntu-22.04

     steps:
       - name: step 1
         run: echo "multiple steps"

       - name: step 2
         run: pwd

       - name: step 3
         run: touch app.txt

       - name: step 4
         run: echo " this is multiple steps practice"
          
        
