name: myworkflow

on: 
  push:

jobs:
  test:
     runs-on: ubuntu-latest

     steps: 
       - name: Welcome
         run: |
           hostname
           pwd
           whoami
           date
           who
           time
     
