name: myworkflow

on: 
  push:

jobs:
  test:
     runs-on: ubuntu-latest

     steps: 
       - name: Welcome
         run: |
           echo "Hello"
           echo " welcome"
           echo " Github actions"
     
