name: GITHUB ACTIONS BASICS

on: 
  push:

jobs:
  Inspect:
     runs-on: ubuntu-24.04

     steps:
       - uses: actions/checkout@v4

       - name: print current directory
         run: pwd
       - name: show all files
         run: ls -la
       - name: display the hello file
         run: cat hello.yml
       - name: print today date
         run: date
       - name: disply kernal version
         run: uname -a
       - name: create a directory 
         run: mkdir logs
       - name: create a file name surya
         run: touch surya.txt
       - name: keep data in file surya
         run: echo "this is new file addded to repo" >surya.txt
       - name: keep surya file into the logs foldre
         run: mv surya.txt logs/
       - name: to see data of folder logs
         run: ls -la logs
